### ISSUE TITLE
Mute the Translation not found for message id error messages

### ISSUE THREAD

**Issue by robert-j-engdahl** [VitaliiTsilnyk/NGettext#28]
As a follow-up on https://github.com/robert-j-engdahl/ngettext-wpf/issues/44 by @D-Bullock I think that it could be useful with an option to disable the translation not found error in https://github.com/VitaliiTsilnyk/NGettext/blob/a701ac67a9822f71539ac7f81d671d6281790c9d/src/NGettext/Catalog.cs#L286

**Comment by VitaliiTsilnyk** [comment]
Yeah, I agree, those traces are not useful at all, also they are not working on all platforms. I'll remove them and make a new release today or tomorrow.

**Comment by VitaliiTsilnyk** [comment]
Fixed in version 0.6.4
