### ISSUE TITLE
Allow to pass a IFormatProvider to the Get*String functions

### ISSUE THREAD

**Issue by Hugal31** [VitaliiTsilnyk/NGettext#33]
Currently, the only way to use a custom `IFormatProvider` with NGettext is to subclass `CultureInfo`, which is not very convenient.

The `Get*String` methods of ICatalog could take a `IFormatProvider`, so one can use custom formatters. The given `IFormatProvider` would be in charge of formatting numbers and date correctly.

Usage example: I am trying to do a simple "grammar macro" text, which looks like this:

```csharp
String.Format("{0:They} {0:are} coding in C#", myPerson);
```
Which could give `He is coding in C#`, or retrieve a translation with other formatters from the catalog, like `{0:Il} cod{0:ent} en C#`

**Comment by Hugal31** [comment]
Alternatively, we could add a `IFormatProvider CustomFormatProvider` property used instead of the `CultureInfo` if it is not null.

**Comment by VitaliiTsilnyk** [comment]
Implemented in version 0.6.6.
Thank you for suggestion.
